### DISCUSSION TITLE
Is it possible to use cluster with proxy?

### DISCUSSION THREAD

**Discussion by agustin-munoz** [redhat-developer/intellij-kubernetes#736] [Q&A]
Hello,

Currently I am using a cluster I need a proxy to access, in my ~/.kube/config I have something like:

```yaml
- cluster:
    proxy-url: http://127.0.0.1:9090
    server: https://api.ring.example-cloud.com:6443
    insecure-skip-tls-verify: true
  name: ring
```

When I try to read the workloads it ends up always with an error, and if taking a look to netstat I see those SYN_SENT there:

  TCP    10.185.72.179:55003    100.92.18.125:6443     SYN_SENT
  TCP    10.185.72.179:55004    100.92.18.125:6443     SYN_SENT

It is supporting the client the proxy-url spec or can it be set anyway?
