### ISSUE TITLE
Custom resources kind is not watched if it already has instances

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#113]
steps:

1. ASSERT: have custom resource definition existing on cluster
```
echo "apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cars.openshift.pub
spec:
  group: openshift.pub
  names:
    kind: Car
    listKind: CarList
    plural: cars
    singular: car
  scope: Cluster
  subresources:
    status: {}
  version: v1" | kubectl apply -f - 
```
2. ASSERT: have custom resource instances that match the spec of this definition
```
echo "apiVersion: openshift.pub/v1
kind: Car
metadata:
  name: bmw
spec:
  date_of_manufacturing: "2014-07-01T00:00:00Z"
  engine: N57D30" | kubectl apply -f -
```
3. EXEC: launch plugin, unfold "Custom Resources"
4. ASSERT: your custom resource definition among the entries that are listed
5. EXEC: unfold your custom resource definition
6. ASSERT: it shows 1+ existing instances
7. EXEC: create a new instance of this definition
```
echo "apiVersion: openshift.pub/v1
kind: Car
metadata:
  name: alfa
spec:
  date_of_manufacturing: "2016-07-01T00:00:00Z"
  engine: CQ123456" | kubectl apply -f -

```
Result:
The tree wont get updated to show the new entry. Same is true when you delete your existing instance

Expected result:
The tree gets updated to show the new entry. The same is true for deleting the existing instance
