### ISSUE TITLE
Should display the custom resources in the version that has the highest priority

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#117]
steps:
1. ASSERT: make sure you have a crd with different versions:
```
echo "apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cars.openshift.pub
spec:
  group: openshift.pub
  names:
    kind: Car
    listKind: CarList
    plural: cars
    singular: car
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
  names:
    kind: Car
    plural: cars" | kubectl apply -f - 
```
2. ASSERT: make sure that you custom resources in all versions that are defined in the custom resource definition:
```
echo "apiVersion: openshift.pub/v1alpha1
kind: Car
metadata:
  name: bmw
spec:
  date_of_manufacturing: "2014-07-01T00:00:00Z"
  engine: N57D30" | kubectl apply -f -
```
```
echo "apiVersion: openshift.pub/v1beta1
kind: Car
metadata:
  name: bmw
spec:
  date_of_manufacturing: "2014-07-01T00:00:00Z"
  engine: N57D31" | kubectl apply -f -
```
3. EXEC: launch the plugin and look into "Custom Resources" > cars what the decoration is telling you about the version that is displayed

Result:
`v1alpha1` cars are displayed
![image](https://user-images.githubusercontent.com/25126/98585929-461c5e80-22c8-11eb-9b3b-33debe535e21.png)

Expected result:
`v1beta1` resources are displayed
