### ISSUE TITLE
Pods for a deployment are not listed. An error is displayed instead.

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#281]
**Steps:**
1. ASSERT: make sure that you have 1+ deployment
1. EXEC: create the following pod (no labels!)
```
---
apiVersion: "v1"
kind: "Pod"
metadata:
  creationTimestamp: "2021-10-19T16:16:46Z"
  name: "countdown-42a"
spec:
  containers:
  - command:
    - "bin/bash"
    - "-c"
    - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
    image: "centos:7"
    name: "counter"
```
1. EXEC: in the tool window, go to **Workloads > Deployments > <your deployment> > <list of its pods>**

**Result:**
The pods are not listed, an error is listed instead
![image](https://user-images.githubusercontent.com/25126/137961080-cff5dbd7-5510-4ae1-b72b-44dfff4f8c1b.png)
