### ISSUE TITLE
deployments in the tree are collapsed upon changes

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#286]
**Steps:**
1. ASSERT: have a deployment yml opened in an editor
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
  labels:
    app: nginx-rolling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rolling
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
```
1. EXEC: push the editor content to the cluster
1. ASSERT: in the resource tree (tool window): unfold **Workloads > Deployments > ngnix-rooling > ngnix-rolling-XXXX**
1. EXEC: editor: modify the **replicas** in the yaml & push to the cluster

**Result:**
In the resource tree the deployment **ngnix-rolling** is collapsed, hiding the pods that belong to it.
