### ISSUE TITLE
pod that's not ready is listed as ready 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#290]
This was reported in https://github.com/redhat-developer/intellij-kubernetes/pull/282#discussion_r736236112

**Steps:**
1. EXEC: create a deployment
```
---
apiVersion: "v1"
kind: "Pod"
metadata:
  creationTimestamp: "2021-10-19T16:16:46Z"
  name: "countdown-42a"
spec:
  containers:
  - command:
    - "bin/bash"
    - "-c"
    - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
    image: "centos:7"
    name: "counter"
```
2. EXEC: go to **Workload > Pods > countdown-42a** and verify the icon
3. EXEC: do the same in vscode

**Result:**
VSCode displays the pod as not-ready with a red dot in the icon
![image](https://user-images.githubusercontent.com/25126/138876120-b6fe8774-da34-4745-8826-f0dd611ea86e.png)
While intellij-kubernetes displays the pod as running/ready with a green dot:
![image](https://user-images.githubusercontent.com/25126/138876205-3e1773f5-4fe3-4a75-bc55-44a2caa754c3.png)

**Comment by adietish** [comment]
**Steps:**
1. EXEC: create a pod with the following yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: apache
      image: httpd:2.4.54
      ports:
        - containerPort: 80
```
1. EXEC: look at it's icon in the resource tree

**Result:**
It is displayed with a green dot which means that it's ready. VScode displays it with a red dot.
