### ISSUE TITLE
Push notification should not be shown if editor violates schema

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#307]
**Steps:**
1. EXEC: open ctx menu for project & select **New > File > nginx-rolling.yml**
2. EXEC: paste the following content:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
  labels:
    app: nginx-rolling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080
```
3. ASSERT: "Push" notification appears
4. EXEC: change **spec: > replicas: 1** to `"a"`
5. ASSERT: "a" is highlighted as incompatible value
![image](https://user-images.githubusercontent.com/25126/143428155-bae0471d-b928-47eb-8390-1d60973370f5.png)

**Result:**
"Push" notification is still present

**Expected result:**
"Push" notification should not be displayed since we have invalid content. 

6. EXEC: hit "Push" in the notification

**Result:**
Nothing happens, no error is displayed, "Push" notification stays

**Expected result:**
"Push" notification should disappear and get replaced by an error since the push did not succeed, the server refused the content because of the schema violation.
