### ISSUE TITLE
String values in yaml should not be quoted if not required

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#310]
taken from https://github.com/redhat-developer/intellij-kubernetes/issues/307#issuecomment-980537056

**Steps:**
1. ASSERT: have a pod running
2. EXEC: open pod in editor
ex. 
```
---
apiVersion: "v1"
kind: "Pod"
metadata:
  creationTimestamp: "2021-11-16T18:26:52Z"
  generateName: "mehdb-"
  labels:
    app: "mehdb"
    controller-revision-hash: "mehdb-9b596f6c9"
    statefulset.kubernetes.io/pod-name: "mehdb-0"
    ...
```
3. EXEC: retrieve the same pod with kubectl `kubectl get pod <name>`
ex.
``` 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-16T18:26:52Z"
  generateName: mehdb-
  labels:
    app: mehdb
    controller-revision-hash: mehdb-9b596f6c9
    statefulset.kubernetes.io/pod-name: mehdb-0
```
4. EXEC: compare `kind:`

**Result:**
The plugin displays `kind: "Pod"` whereas kubectl is showing `kind: Pod`
