### ISSUE TITLE
Invalid kubenetes yaml/json shown seems not to be updated

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-kubernetes#322]
In the Tekton plugin, I create a new pipeline, the content is:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  resources:
    - name: pipeline-resource-type
      type: pipeline-type
  tasks:
    - name: foo
      taskRef:
        name: build-app
```

Trying to put single quotes around the `foo` value, I have an error message that is popped:

![image](https://user-images.githubusercontent.com/695993/145975186-4be0409d-b09c-446f-9ee4-01c60aae70c2.png)

Seems it is not updated / reset as changing `foo` to `bar` does not change the error message
