### ISSUE TITLE
Editor: Cannot push namespaced crd

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#331]
related to https://github.com/redhat-developer/intellij-kubernetes/issues/319#issuecomment-993488167

**Steps:**
1. EXEC: File > New > crd-helm.cattle.io.yml
2. EXEC: in editor paste the following (taken from https://github.com/k3s-io/helm-controller/blob/master/manifests/crd.yaml):
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.helm.cattle.io
  namespace: kube-system
spec:
  group: helm.cattle.io
  version: v1
  additionalPrinterColumns:
    - name: Job
      type: string
      description: Job associated with updates to this chart
      JSONPath: .status.jobName
    - name: Chart
      type: string
      description: Helm Chart name
      JSONPath: .spec.chart
    - name: TargetNamespace
      type: string
      description: Helm Chart target namespace
      JSONPath: .spec.targetNamespace
    - name: Version
      type: string
      description: Helm Chart version
      JSONPath: .spec.version
    - name: Repo
      type: string
      description: Helm Chart repository URL
      JSONPath: .spec.repo
    - name: HelmVersion
      type: string
      description: Helm version used to manage the selected chart
      JSONPath: .spec.helmVersion
    - name: Bootstrap
      type: boolean
      description: True if this is chart is needed to bootstrap the cluster
      JSONPath: .spec.bootstrap
  names:
    kind: HelmChart
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
```
**Result:**
Push fails with the following error: 
```
io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:kube-system. Operation namespace:default.
```
