### ISSUE TITLE
Editing fails if you're not admin on your cluster

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#348]
taken from: https://github.com/redhat-developer/intellij-kubernetes/issues/319#issuecomment-1028689553

**Steps:**
1. EXEC: create a sandbox at https://developers.redhat.com/developer-sandbox & log into it
2. EXEC: in sandbox web frontend: copy the oc command & execute it in your local terminal
3. EXEC: in IJ: create a new file `pod.yml` and paste the following into it:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```
**Result:**
The editor errors telling you that it cannot retrieve the custom resource definitions in the sandbox:
![image](https://user-images.githubusercontent.com/25126/152326520-398f8338-5fa1-4a26-8385-6077cfec3d2a.png)
That's expected because only admins have access to the crds.
