### ISSUE TITLE
editor: Only heals after re-authenticating into the sandbox if you type in the editor

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#375]
related to #374 

**Steps:**
1. ASSERT: have an outdated token on the sandbox
```
$ oc get pod
error: You must be logged in to the server (Unauthorized)
```
2. ASSERT: have a resource yml file, ex.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080

```
3. EXEC: open the resource yml file in an editor
4. ASSERT: editor shows an error notification, telling you that you're not authorized
![image](https://user-images.githubusercontent.com/25126/161942201-1fe7b890-34e8-4bdf-ae91-ff9c750957e3.png)
5. EXEC: Browse to your web console, log in, copy the login command and execute it in the terminal 
6. EXEC: get back to the editor
7. ASSERT: Editor still says that you're not authorized
![image](https://user-images.githubusercontent.com/25126/161949441-c3c906de-e473-4e01-b2e4-7d84806327e1.png)
8. EXEC: type in the editor

**Result:**
Editor heals and is back to work

**Expected result:**
Editor should notice that authorization happened and the error should disappear without the user having to type in the editor.
