### ISSUE TITLE
Push notification does not go away even though I just pushed

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#376]
**Steps:**
1. ASSERT: make sure that you're connected to the Red Hat Sandbox (time consumed when pushing is higher than local cluster)
1. EXEC: open k8s resource yaml file in editor
ex. 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
```
2. EXEC: if resource doesn't exist yet, push it to create it on the cluster. 
3. EXEC: add label: `metadata > labels: jedi: yoda`
4. ASSERT: push notification appears prompting you to update the resource on the cluster ("update existing resource")
![image](https://user-images.githubusercontent.com/25126/162226557-9eb5c275-09b2-417b-9893-6dd51306554c.png)
5. EXEC: hit "Push" link in the notification

**Result:**
Push notification is still displayed even though I just pushed. 
![image](https://user-images.githubusercontent.com/25126/162226877-c876cfac-873b-4143-9894-4c933b4d54b5.png)

**Expected result:**
Push notification should be hidden and not displayed any more since I cluster & editor should be on the same page
