### ISSUE TITLE
As a user i want to be able to see my custom resource exists even though I have no perms to list those

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#383]
**Steps:**
1. ASSERT: make sure that you're connected to a cluster where you dont have permissions to list the custom resource (ex. RH sandbox):
![image](https://user-images.githubusercontent.com/25126/162765211-00192759-b032-4125-ad6f-1ff02d5f2b84.png)
2. ASSERT: identify a custom resource that is supported and that you therefore can create (ex. knative services on RH sandbox)
3. EXEC: open an editor with the yaml/json for a supported custom resource that doesn't exist yet. 
ex. knative service on RH sandbox:
```
---
apiVersion: "serving.knative.dev/v1"
kind: "Service"
metadata:
  labels:
    jedi: "yoda"
  name: "helloworld-go"
spec:
  template:
    spec:
      containers:
      - image: "gcr.io/knative-samples/helloworld-go"
        env:
        - name: "TARGET"
          value: "Go Sample v1"
```
5. Then push it to the cluster, so that the resource gets created on the cluster

**Result:**
i have no way to know that my new resource exists. In the web console, they are listing my resource in the topology
![image](https://user-images.githubusercontent.com/25126/162766371-66acf538-1cca-46fc-9fe6-1168783c1f17.png)

**Expected result:**
I want my resource shown in the resource tree if it exists.
