### ISSUE TITLE
editor should report unreachable host, not socket closed

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#406]
**Steps:**
1. ASSERT: have 2 clusters, cluster1 set as current, cluster2 not reachable (ex. minikube stopped) 
2. ASSERT: have a resource file to edit
ex. job.xml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
  labels:
    jedi: luke
spec:
  template:
    spec:
      containers:
        - name: counter
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never

```
3. EXEC: open editor with the resource file
4. ASSERT: editor notifies you that you can create a new resource (or update an existing one) on the current context cluster1
5. EXEC: switch to cluster2 as current context

**Result:**
Editor reports "Socket closed"
![image](https://user-images.githubusercontent.com/25126/168635762-adb4dda9-1fc7-4c82-b2e9-e09b8d4319d4.png)

**Expected result:**
Editor should report that cluster2 is not reachable.
