### ISSUE TITLE
Should error if there's no current context

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#426]
**Steps:**
1. ASSERT: have a cluster in kube config
2. ASSERT: make sure it's **NOT** set as currect context
(to remove it run `kubectl config unset current-context`)
3. ASSERT: have a valid yaml file with the following content:
```
apiVersion: v1
data:
  username: YWRtaW4=222
  password: MWYyZDFlMmU2N2Rm
kind: Secret
type: Opaque
```
3. EXEC: launch plugin, open your file in an editor

**Result:**
The editor shows no error notification

**Expected result:**
The editor should show an error notification that informs that there's no current context.
