### ISSUE TITLE
Editing resource without name is reported as unreachable cluster

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#427]
**Steps:**
1. ASSERT: have a yaml file with a resource that has no name:
```
apiVersion: v1
data:
  username: YWRtaW4=222
  password: MWYyZDFlMmU2N2Rm
kind: Secret
type: Opaque
```
2. EXEC: open it in an editor

**Result:**
Error notification is displayed telling you that the cluster could not be reached. In the details you can discover that the problem is that the resource has no metadata.
![grafik](https://user-images.githubusercontent.com/25126/175059758-29f90c68-1377-41df-a1ca-dda93d6f39f7.png)
