### ISSUE TITLE
Allow to push resources with generateName instead of name field

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#437]
I'm trying to push a taskrun on the cluster with the `generateName` field set because i want the cluster to name it randomly as i don't want to handle collisions myself. 
Right now this is not possible because the plugin recognize no name is set.

![image](https://user-images.githubusercontent.com/49404737/176658212-679408f1-c68b-4c78-9036-5d1b6089757b.png)

Example taskrun (in taskref name replace `npm-fail` withut a task you have on your cluster which does not require any input)
```
apiVersion: "tekton.dev/v1beta1"
kind: "TaskRun"
metadata:
  generateName: "npm-fail-"
spec:
  taskRef:
    name: "npm-fail"
```
