### ISSUE TITLE
editor should keep error that happened

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#442]
**Steps:**
1. ASSERT: have minikube with tekton
2. ASSERT: make sure that you dont have the following 2 tasks:
* `print-date`
* `add-task-2`
1. EXEC: open the following in an editor (our toolbar with actions to push/pull/diff should get activated):
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: add-task-2
spec:
  params:
    - name: first
      description: the first operand
    - name: second
      description: the second operand
  results:
    - name: sum
      description: the sum of the first and second operand
  steps:
    - name: add
    - name: sub
    - image: ok
    - image: no
```
3. EXEC: push the file to the cluster
4. ASSERT: push fails with the following error:
![grafik](https://user-images.githubusercontent.com/25126/176971267-4b15cb02-fbf9-47fe-a185-6b77ba453e64.png)
```
Failure executing: POST at: https://192.168.64.10:8443/apis/tekton.dev/v1beta1/namespaces/default/tasks. Message: admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal bool into Go struct field Step.spec.steps.image of type string. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal bool into Go struct field Step.spec.steps.image of type string, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
```
1. EXEC: open the following in an editor:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-date
  annotations:
    description: |
      A simple task that prints the date
spec:
  results:
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
    - name: current-date-human-readable
      description: The current date in human readable format
  steps:
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date +%s | tee $(results.current-date-unix-timestamp.path)
    - name: print-date-human-readable
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date | tee $(results.current-date-human-readable.path)
```
1. EXEC: push it to the cluster
2. EXEC: switch to the editor `add-task-2`
**Result:**
Editor has no error any more, instead it prompts you to push.
![grafik](https://user-images.githubusercontent.com/25126/176971162-0dd89999-1586-49cc-9a8c-8bde7ef1ac91.png)
