### ISSUE TITLE
cannot follow logs for a pod with multiple containers

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#461]
**Steps:**
1. EXEC: create a pod with 2+ continers
```
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80  
  - name: container-2
    image: alpine
    command: ["watch", "wget", "-qO-", "localhost"]
```
1. EXEC: in resource tree: select Workloads > Pods > multi-container-pod & pick "Follow Log" in the ctx menu

**Result:**
Terminal opens and displays the following client error:
```
r-1 container-2]","reason":"BadRequest","code":400}tatus":"Failure","message":"a container name must be specified for pod multi-container-pod, choose one of: [containe
```

***Expected result:**
If there are several containers I should be able to choose the container I want to follow logs for.
