### ISSUE TITLE
resource tree: pods for jobs are not displayed

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#478]
**Steps:**
1. EXEC: create a job:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: endlessdate
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
        - name: counter
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for (( ;; )); do date +\"%H%m%s\"; sleep 2; done"
      restartPolicy: Never
```
2. EXEC: navigate to **Workloads > Jobs > enlessdate** and expand it

**Result:**
No pod for the job **endlessdate** is listed, it is displayed in **Pods** though
