### ISSUE TITLE
Pushing a 2nd time errors without empty error details

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#485]
**Steps:**
1. EXEC: open the following in an editor:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```
2. EXEC: push to the cluster and have the pod created
3. ASSERT: after the push you're informed that the pod is different on the cluster (clutter was added) and that you can pull
4. EXEC: hit "Ignore" so that the notification disappears
5. EXEC: Push the editor to the cluster

**Result:**
The push fails:
![grafik](https://user-images.githubusercontent.com/25126/190197674-8ffd70a5-4265-4610-bbdd-97f39d2579c8.png)
If you click the "Details" link you get a huge error balloon without text:
![grafik](https://user-images.githubusercontent.com/25126/190197781-8b738f17-0a37-4cde-bf68-d81d923cad49.png)
