### ISSUE TITLE
View seems to select wrong context

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-kubernetes#49]
I have a strange configuration but worth testing.
In my kubeconfig I have 2 distincts contexts defined for the same cluster and user but pointing to different projects. One of them does not exists anymore.
So the context are:

- `demojeff/clusterurl/token`
- `jbosstools/clusterurl/token`

demojeff project does not exist anymore on the cluster.
Although my kubeconfig says the current-context is `jbosstools/clusterurl/token`, the view selects `demojeff/clusterurl/token`
And selecting `jbosstools/clusterurl/token` as the current context does not seem to work

**Comment by adietish** [comment]
@jeffmaury I can't reproduce this. I have the following valid context:
```
- context:
    cluster: minikube
    namespace: foo
    user: minikube
  name: erroneous
```
I then created the following **"erroneous"** context with an nonexistent namespace:
```
- context:
    cluster: minikube
    namespace: tekton-pipelines
    user: minikube
  name: minikube
```

IJ starts up and shows the following:
![image.png](https://images.zenhubusercontent.com/5c924840b65bca7678bd233e/515a58f2-315d-424c-868e-277297c621c4)

Switching to the valid **"minikube"** works fine for me.
What am I missing?
