### ISSUE TITLE
Error balloon does not go away if I switch editor

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#491]
follows up on #485

**Steps:**
1. ASSERT: have an editor opened
1. EXEC: open the following in an editor
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```
2. EXEC: push it to the cluster 2x
3. ASSERT: 2nd push (or fist if the pod already existed) errors
4. EXEC: click on "Details" link
5. ASSERT: error balloon shows up
6. EXEC: (do not close the error balloon) switch to another editor

**Result:**
Error balloon is still visible even though it belongs to the editor that is now overlapped by the current editor.
![grafik](https://user-images.githubusercontent.com/25126/191530026-390e4a04-56b6-4c24-92a8-c545d2e9ac0a.png)
