### ISSUE TITLE
when switching current namespace, editor still saves to previous namespace

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#492]
**Steps:**
1. ASSERT: have 2+ namespaces (ex. on minikube: "default" & "kube-public")
2. ASSERT: have "default" set as current namespace
3. EXEC: open the following in an editor:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```
4. EXEC: switch to "kube-public" namespace
5. EXEC: push editor to cluster

**Result:**
Pod is created in "default" even though I switched to the "kube-public" namespace
