### ISSUE TITLE
Editor: notification disappears when I clean clutter

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#503]
**Steps:**
1. ASSERT: make sure that you dont have a pod `multi-pod2` on your cluster
2. EXEC: open the following in an editor:
```
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod2
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: alpine-container
      image: alpine
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo Hello, World!!! > /pod-data/index.html; sleep 1; done"]
```
3. ASSERT: notification appears that you can push and create a new resource on the cluster
4. EXEC: hit "remove metadata clutter" action in the editor toolbar

**Result:**
Notification disappears even though the editor can still be pushed to the cluster and create a new resource.

This bug is not critical because you can still push to the cluster via the action in the toolbar.
