### ISSUE TITLE
Support init containers

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#523]
According to the [docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) init containers are specialized containers that run before app containers in a [Pod](https://kubernetes.io/docs/concepts/workloads/pods/). Init containers can contain utilities or setup scripts not present in an app image.

The OpenShift docs are at https://docs.openshift.com/container-platform/4.11/nodes/containers/nodes-containers-init.html

In the reviews to the jetbrains plugin there are several people requesting support for init container:
* https://plugins.jetbrains.com/plugin/10485-kubernetes/reviews#review=74755 <img width="1016" alt="image" src="https://user-images.githubusercontent.com/25126/203525864-599023df-01b2-412f-b4ea-cce7f9e26589.png">
* https://plugins.jetbrains.com/plugin/10485-kubernetes/reviews#review=74758 <img width="990" alt="image" src="https://user-images.githubusercontent.com/25126/203526007-10651045-ec97-409d-9c3c-4522a8c2bc9f.png">

**Comment by adietish** [comment]
Here's an example of a pod with a init container:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-initcontainers
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  initContainers:
    - name: sleepy
      image: alpine
      command: ['sleep', '60']
  containers:
    - name: ngnix
      image: ngnix:latest
      ports:
        - containerPort: 8080
```
If you push the yaml to the cluster, the pod gets created and put into "Init"-state as long as the init-container is not finished successfully:
> nginx-initcontainers     0/1     Init:0/1           0               6s

via `kubectl describe pod nginx-initcontainers` one then can have a look at the init-container in order to be able to look at it's logs:
>Name:             nginx-initcontainers
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.64.2
Start Time:       Wed, 23 Nov 2022 11:47:48 +0100
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:               172.17.0.10
IPs:
  IP:  172.17.0.10
Init Containers:
  sleepy:
    Container ID:  docker://70756e2001c25a65727c6918bc61e55c9057e1bf349380e49e928eda517ebe49
    Image:         alpine
    Image ID:      docker-pullable://alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
      60
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 23 Nov 2022 11:47:51 +0100
      Finished:     Wed, 23 Nov 2022 11:48:51 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6jkpl (ro)
Containers:
  ngnix:
