### ISSUE TITLE
Can push yml resource without a name but no resource is created, "pull" and "diff" actions do nothing

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#530]
This is **IT No 36**

**Steps:**
1. EXEC: File > New > YML file -> paste the following resource without name 
```
apiVersion: v1
metadata:
  labels:
    jedi: yoda
data:
  username: YWRtaW4=222
  password: MWYyZDFlMmU2N2Rm
kind: Secret
type: Opaque
```
3. EXEC: Push to the cluster

**Result:**
No resource is created, no error is displayed. Neither "Pull", "Diff" nor "Push" have any effect, they do nothing.

**Expected Result:**
Error notification resource could not be retrieved (details: name missing)
