### ISSUE TITLE
"Follow Logs" for a container that's waiting will print error response into the console 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#534]
**Steps:**
1. EXEC: create a new file with the following content:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-initcontainers
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  initContainers:
    - name: quickdie
      image: alpine
      command: ['echo']
    - name: inthemiddle
      image: alpine
      command: ['echo']
    - name: lastone
      image: alpine
      command: ['sleep', '60']
  containers:
    - name: ngnix
      image: ngnix:latest
      ports:
        - containerPort: 8080
```
2. EXEC: Push the file to the cluster (pod will be created and shows up in [cluster] > Workloads > Pods
4. EXEC: select the pod ** nginx-initcontainers** and choose "Follow logs" in the context menu
5. EXEC: make sure container **ngnix** is selected

**Result:**
An error is printed to the console:
```
```

**Expected result:**
An error pane should be displayed telling the user that the plugin could not connect to the container
