### ISSUE TITLE
logs/terminal: allow to inspect error details

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#537]
**Steps:**
1. EXEC: create a deployment via the following:
```
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "nginx"
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - image: "nginx"
        name: "nginx"
        ports:
        - containerPort: 80
          protocol: "TCP"
      initContainers:
      - image: "alpine"
        name: "init1"
```
2. EXEC: select the deployment and pick "Terminal" in the context menu
3. EXEC: select the container "init"
4. ASSERT: an error is displayed in the terminal pane. 
<img width="976" alt="image" src="https://user-images.githubusercontent.com/25126/203978699-e045ef56-fb1d-49f4-ac96-7164868e56d7.png">
5. EXEC: try to figure out what exactly went wrong

**Result:**
You just get the generic message that the terminal could not connect to the container. There are no details about why this happened.

**Expected result:**
You should be able to inspect the details of the connection error
