### ISSUE TITLE
Feature Request: Support Multi Resource Files

### ISSUE THREAD

**Issue by berndwaibel** [redhat-developer/intellij-kubernetes#549]
I use yaml files, which contain more than one resource kind. All marked as invalid.
It seems there have to be only the same kind of resource per one file.
Feature Request: support Multi Resource Files

Example
```
apiVersion: v1
kind: Secret
metadata:
  name: jhipster-grafana-credentials
  namespace: default
data:
  username: xxxxxxx
  password: xxxxxxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-grafana
```

Error Message:
`Invalid kubernetes yaml/json`
