### ISSUE TITLE
Editor: should not be able to diff if the resource in the editor doesn't exist on the cluster

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#550]
**Steps:**
1. ASSERT: make sure that there's no pod `busybox` on the cluster
2. EXEC: open an editor with the following content:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: busybox
      image: busybox
      ports:
        - containerPort: 8080
```
3. EXEC: hit "Diff" in the editor toolbar

**Result:**
The diff dialog opens up with the remote portion empty. 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/25126/211082247-0d35eb32-18bf-492e-bbaa-8988c7158a5e.png">

**Expected result:**
I should not be able to open the diff dialog.
