### ISSUE TITLE
Tree: custom resource only appears when manually refreshing

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#558]
related to #500 

**Steps:**
1. ASSERT: in resource tree: expand `[cluster] > Custom Resources`
2. EXEC: push the following crd to the cluster:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myplatforms.contoso.com
spec:
  group: contoso.com
  names:
    plural: myplatforms
    singular: myplatform
    kind: MyPlatform
    shortNames:
      - myp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appId:
                  type: string
                language:
                  type: string
                  enum:
                    - csharp
                    - python
                    - go
                os:
                  type: string
                  enum:
                    - windows
                    - linux
                instanceSize:
                  type: string
                  enum:
                    - small
                    - medium
                    - large
                environmentType:
                  type: string
                  enum:
                    - dev
                    - test
                    - prod
                replicas:
                  type: integer
                  minimum: 1
              required: ["appId", "language", "environmentType"]
          required: ["spec"]
```
2. ASSERT: `[cluster] > Custom Resources > myplatform` appears in the tree
3. EXEC: push the following custom resource to the cluster:
```yaml
apiVersion: contoso.com/v1alpha1
kind: MyPlatform
metadata:
  name: test-go-app
  labels:
    jedi: luke
spec:
  appId: testgoapp
  language: go
  os: linux
  instanceSize: small
  environmentType: dev
  replicas: 3
```
**Result:**
Custom resource `test-go-app` does not appear as child to `myplatform`. It only appears once I manually refresh the root node `[cluster]`
