### ISSUE TITLE
Editor: notifies me that my "old" (before renaming it) resource was deleted

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#559]
**Steps:**
1. EXEC: open the following yaml in an editor and push it to the cluster:
```yaml
---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "alpine1"
spec:
  containers:
  - image: "alpine"
    name: "alpine"
    ports:
    - containerPort: 8080
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
```
2. EXEC: change the name to `alpine2` and push it to the cluster
3. EXEC: in the tree: delete `alpine1`

**Result:**
Editor notifies you that `alpine1` was deleted. It should not since I am now editing `alpine2`

This is caused by the following that was erroneously migrated in #500:
`NonCachingSingleResourceOperator` is not specifying the name of the resource that should be used. It is thus watching all resources of the same kind in the namespace of the given resource:
```kotlin
fun watch(resource: HasMetadata, watcher: Watcher<HasMetadata>): Watch? {
        ...
        val op = createOperation(genericKubernetesResource)
        ...
        op.watch(GenericKubernetesResourceWatcherAdapter(watcher))
        ...
```
