### ISSUE TITLE
Dialog "This file does not belong to the project" when trying to edit new file

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#605]
**Steps:**
1. EXEC: create a new resource file in your project, using an external (!!) editor (ex. vi, echo into a file, etc.)
You wont be able to reproduce the bug if you use a file that you already opened in IDEA. Either the editor already made the file editable or you may have answered the prompt already. The enablement is permanent.
```
---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "alpine2"
  labels:
    jedi: "luke"
spec:
  containers:
  - image: "alpine"
    name: "alpine"
    ports:
    - containerPort: 8080
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
```
2. EXEC: in IDEA: open the file and try to edit it

**Result:**
You are prompted with a dialog that tells you "This file does not belong to the project"
<img width="542" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/b091c98f-1dab-4ec2-88a4-b16280c6cbc1">
