### ISSUE TITLE
When using sandbox the editor is freezing for a few seconds on startup

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#613]
**Steps:**
1. EXEC: have Red Hat Sandbox as current cluster
1. EXEC: create the quarkus kubernetes-quickstart app
```bash
quarkus create app org.acme:kubernetes-quickstart \
    --extension='resteasy-reactive,kubernetes,jib'
```
2. EXEC: run `./mvnw clean package`
3. EXEC: import it into intellij
4. EXEC: open the k8 resource file `target/kubernetes/openshift.yml` in an editor
5. EXEC: scroll around until the editor is freezing

**Result:**
At some point the editor is freezing for a few seconds (maybe 4s) before it displays the notification

**Comment by adietish** [comment]
The freeze is caused by `PushNotification#show` that calls `EditorResource#getState` to see if a resource is **New** or an **Modified** for a resource on the cluster. For a new resource the notification would display "Push to create resource X?", for a modified resource it would show "Push to update resource X?". `EditorResource#getState` would then reach out to the cluster and check. `PushNotification#show` is executed in the UI thread and thus freeze the UI thread.

**Comment by adietish** [comment]
The freeze is caused by `PushNotification#show` that calls `EditorResource#getState` to see if a resource is **New** or an **Modified** for a resource on the cluster. For a new resource the notification would display "Push to create resource X?", for a modified resource it would show "Push to update resource X?". `EditorResource#getState` would then reach out to the cluster and check. `PushNotification#show` is executed in the UI thread and thus freeze the UI thread.

**Comment by adietish** [comment]
The freeze can only be experienced when using the Red Hat Developer Sandbox (or any remote cluster) and when using a multi-resource document like the document pasted below. It is generated when https://github.com/adietish/openshift-quickstart is built (`mvn clean package`) or when the project is scaffolded with the `quarkus` command line show above.
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  dockerImageRepository: docker.io/adietish/openshift-quickstart
  lookupPolicy:
    local: true
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quickstart
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: openshift-quickstart
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: openshift-quickstart:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: openshift-quickstart
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - openshift-quickstart
        from:
          kind: ImageStreamTag
          name: openshift-quickstart:1.0.0-SNAPSHOT
      type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: openshift-quickstart
```
