### ISSUE TITLE
Schema validation does not work with multi-resource documents

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#630]
**Steps:**
1. EXEC: open the following yaml in an editor
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: openshift-quickstart
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quickstart
  name: openshift-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: openshift-quickstart
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-06-30 - 12:24:49 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: openshift-quickstart
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: adietish/openshift-quickstart:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: openshift-quickstart
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
```
2. EXEC: put your cursor to the 2nd resource, a `Deployment`
3. EXEC: inspect the schema that is applied. It is shown in the right corner of the status bar:

**Result:**
The schema that is applied still is `Service` (first resource in the document)
<img width="1030" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/697ed4cc-3c3b-4e12-8272-791aec2abde2">

**Comment by adietish** [comment]
It very much looks like the current platform schema validation framework only supports using a single schema file per type. It seems unable to use multiple schema files per json/yaml files that shall be validated (multi-resource file where individual resources are separated by `---`). If this is confirmed we'd have to get away from or extend the platform implementation.

**Comment by adietish** [comment]
in vscode this was requested and they found a workaround indicating the schemas: https://github.com/redhat-developer/vscode-yaml/issues/702#issuecomment-1048518781

**Comment by adietish** [comment]
I tried to provide `KubernetesSchemaProvider`s which would return `true` if one of the resources in the file match the typeinfo in the schema provider:

```java
	override fun isAvailable(file: VirtualFile): Boolean {
		return ApplicationManager.getApplication().runReadAction(
			Computable {
				val fileContent = String(file.contentsToByteArray(true))
				val resources = EditorResourceSerialization.deserialize(fileContent, file.fileType, null)
				resources.any { resource ->
					info.kind == resource.kind
							&& info.apiGroup == resource.apiVersion
				}
			})
	}
```

But this results in no schema being considered at all.

**Comment by adietish** [comment]
I dug into the json plugin/platform and found out that the validation is done on behalf of `JsonSchemaComplianceChecker`.
Interestingly `JsonSchemaComplianceChecker#annotate()` is called 3 times for the 3 resources. The root schema is the deployment schema though. Maybe if we can provide a composite schema which holds the 3 schema would help work around it.

```
    public void annotate(@NotNull PsiElement element) {
```

**Comment by adietish** [comment]
I talked to Yann Cébron on Jetbrains Slack #intellij-platform and he told me that he'd investigate the possibilities to use several schemas to validate a single json/yaml file.

**Comment by adietish** [comment]
I didn't hear back from Yann. I'll have to ask him again since erroneous validation errors in multi-resource documents hurt the user experience a lot. Schema validation is basically useless.
I have to investigate how the jetbrains plugin handles the situation. There's nothin I can reuse though since it is not opensource.

**Comment by adietish** [comment]
According to chatgpt this can be achieved in the following way:

```
Got it! Since Kubernetes YAML files often contain **multiple resources in a single document** (like a `Deployment`, `Service`, `ConfigMap`, etc.), you need a way to validate each resource against its **corresponding schema**.

### **Approach**
1. **Identify individual resources** in a multi-document YAML file.
2. **Determine the schema** based on the resource `kind` (e.g., `Deployment`, `Service`).
3. **Validate each resource against the correct schema**.

---

## **Step 1: Extract Individual Kubernetes Resources**
Each Kubernetes YAML file may contain multiple resources separated by `---`. We need to process them **individually**.

### **Example Multi-Resource YAML**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  key1: value1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
```
Here:
- The first resource (`ConfigMap`) should be validated against the `ConfigMap` schema.
- The second resource (`Deployment`) should be validated against the `Deployment` schema.

---

## **Step 2: Implement a YAML MetaType Provider Based on `kind`**
You can use a `YAMLKeyValueMetaTypeProvider` to apply **different schemas based on the `kind` field**.

### **Provider Implementation**
```java
public class KubernetesResourceMetaTypeProvider extends YAMLKeyValueMetaTypeProvider {
    @Override
    public @Nullable YAMLMetaType getKeyValueMetaType(@NotNull List<String> keys, @NotNull String key) {
        // Only look at the top-level keys (individual K8s resources)
        if (keys.isEmpty() && key.equals("kind")) {
            return new KubernetesKindMetaType();
        }
        return null;
    }
}
```

---

## **Step 3: Define a MetaType for `kind` Detection**
We create a `KubernetesKindMetaType` that dynamically determines the schema based on the `kind` value.

```java
public class KubernetesKindMetaType extends YAMLStringType {
    private static final Map<String, YAMLMappingType> SCHEMA_MAP = Map.of(
        "ConfigMap", new KubernetesConfigMapMetaType(),
        "Deployment", new KubernetesDeploymentMetaType()
    );

    @Override
    public @Nullable YAMLMetaType getPropertyMetaType(@NotNull String propertyName) {
        return YAMLStringType.getInstance();
    }

    @Override
    public void validateKeyValue(@NotNull YAMLKeyValue keyValue, @NotNull ProblemsHolder holder) {
        String kind = keyValue.getValueText();
        if (!SCHEMA_MAP.containsKey(kind)) {
            holder.registerProblem(keyValue.getValue(), "Unknown Kubernetes resource kind: " + kind);
        }
    }

    public static @Nullable YAMLMappingType getSchemaForKind(@NotNull String kind) {
        return SCHEMA_MAP.get(kind);
    }
}
```

---

## **Step 4: Assign the Correct Schema to Each Resource**
Once we detect the `kind`, we must apply the correct schema.

```java
public class KubernetesResourceSchemaProvider extends YAMLKeyValueMetaTypeProvider {
    @Override
    public @Nullable YAMLMetaType getKeyValueMetaType(@NotNull List<String> keys, @NotNull String key) {
        if (keys.isEmpty()) {
            return null;
        }

        if (key.equals("kind")) {
            return new KubernetesKindMetaType();
        }

        // If we already detected "kind", use the correct schema
        if (keys.contains("kind")) {
            String kind = keys.get(keys.indexOf("kind") + 1);
            return KubernetesKindMetaType.getSchemaForKind(kind);
        }

        return null;
    }
}
```

---

## **Step 5: Define Schema for Specific Kubernetes Resources**
Now, we define schemas for each Kubernetes resource type.

### **Example: ConfigMap Schema**
```java
public class KubernetesConfigMapMetaType extends YAMLMappingType {
    public KubernetesConfigMapMetaType() {
        super("Kubernetes ConfigMap");
    }

    @Override
    public @Nullable YAMLMetaType getPropertyMetaType(@NotNull String propertyName) {
        if ("metadata".equals(propertyName)) {
            return new KubernetesMetadataMetaType();
        }
        if ("data".equals(propertyName)) {
            return new KubernetesDataMetaType();
        }
        return null;
    }
}
```

### **Example: Deployment Schema**
```java
public class KubernetesDeploymentMetaType extends YAMLMappingType {
    public KubernetesDeploymentMetaType() {
        super("Kubernetes Deployment");
    }

    @Override
    public @Nullable YAMLMetaType getPropertyMetaType(@NotNull String propertyName) {
        if ("metadata".equals(propertyName)) {
            return new KubernetesMetadataMetaType();
        }
        if ("spec".equals(propertyName)) {
            return new KubernetesDeploymentSpecMetaType();
        }
        return null;
    }
}
```

---

## **Step 6: Register the Provider in `plugin.xml`**
```xml
<extensions defaultExtensionNs="com.intellij">
    <yaml.keyValueMetaTypeProvider implementation="your.plugin.KubernetesResourceMetaTypeProvider"/>
</extensions>
```

---

## **Final Result**
✅ Each resource in a multi-document YAML file is validated **independently** against the correct schema.  
✅ Incorrect fields trigger **schema-based validation errors**.  
✅ Supports **extending new Kubernetes resource types easily**.

---

## **Next Steps**
- Would you like **auto-completion** for Kubernetes resources?
- Do you need **reference resolution** (e.g., resolving `metadata.name` in `selector.matchLabels`)?

Let me know how you'd like to refine this further! 🚀
```
