### ISSUE TITLE
If I push to a cluster and it errors, I am not notified of the error but prompted to push again

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#634]
**Steps:**
1. EXEC: open an editor for the following resource:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: bogus
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
```
2. ASSERT: verify that the `namespace` points to a namespace that doesn't exist on your cluster
3. EXEC: push to the cluster

**Result:**
You are prompted to push again, right after the push, which made the notification disappear, 

**Result:**
When pushing fails, an error should be displayed. You should not be prompted to push again.
