### ISSUE TITLE
subtask to #35: show "Ingress"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#64]
here's how "Ingress" are shown in vscode:
![image](https://user-images.githubusercontent.com/25126/85406985-e1ec3e80-b562-11ea-8033-7e4dac537842.png)

Here's an example ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /apple
          backend:
            serviceName: apple-service
            servicePort: 5678
        - path: /banana
          backend:
            serviceName: banana-service
            servicePort: 5678
```
