### ISSUE TITLE
As a user I'd like help with references in a multi-doc file

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#642]
If you have multi-resource document, you may be resources reference each other within that document. As a user I'd like to have an easy way to jump from the referee to the referencing component and vice-versa.
The jetbrains plugin displays clickable markers to labels (on the left ruler) but it doesnt work for me/I'm unsure how this works).
I'd like to implement those as `InlayHint`.

ex. in the following multi-resource file that was generated by quarkus, there's a service that's referencing a pod (`Service`->`Deployment`, `Ingress`->`Service`)
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-07-14 - 15:53:39 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: openshift-quickstart
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-07-14 - 15:53:39 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quickstart
  name: openshift-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: openshift-quickstart
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-07-14 - 15:53:39 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: openshift-quickstart
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: adietish/openshift-quickstart:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: openshift-quickstart
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-07-14 - 15:53:39 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: openshift-quickstart
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: openshift-quickstart
                port:
                  name: http
            path: /
            pathType: Prefix
```

**Comment by adietish** [comment]
An idea would be to have Ctrl + click scroll to the portion in the editor that is matching.

**Comment by adietish** [comment]
In a 2nd step, we could look up matching resources on the cluster

**Comment by adietish** [comment]
`matchLabel` and `matchExpression` in a `Deployment` target `Pods` which are only available once you push the deployment to the cluster and it then creates these. 
Therefore there's no usecase for references within the same file. Most other resources (`Service`, `DaemonSet`, `StatefulSet`, `Service`, `ReplicaSet`, `Job`, `CronJob`, `NetworkPolicies `, `PodDisruptionBudgets`, `ReplicationController`, `HorizontalPodAutoscaler`) also target `Pod`s, so there's no usecase for them either. 
An exception is `PersistentVolumeClaim` which selects `PersistentVolumes`.

<img width="883" alt="Image" src="https://github.com/user-attachments/assets/45dabc82-cb6d-4af5-8811-332957360009" />

Here's an example of `PVC` and `PV`:
```yaml
# --------------------------
# PersistentVolume 1 (targeted by PVC with matchLabels)
# --------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-labels
  labels:
    pvc-target: labels          # Label for direct matching
    storage-tier: ssd           # Additional label (not required for binding)
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual       # Disables dynamic provisioning
  hostPath:
    path: /mnt/data-labels

---
# --------------------------
# PersistentVolume 2 (targeted by PVC with matchExpressions)
# --------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-expressions
  labels:
    environment: production      # Label for matchExpressions
    region: us-west              # Label for matchExpressions (key existence)
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual       # Disables dynamic provisioning
  hostPath:
    path: /mnt/data-expressions

---
# --------------------------
# PVC 1: Uses matchLabels
# --------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-labels
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pvc-target: labels         # Direct label match

---
# --------------------------
# PVC 2: Uses matchExpressions
# --------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-expressions
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchExpressions:
      - key: environment
        operator: In             # Value must be in the list
        values: [production, staging]
      - key: region
        operator: Exists         # Key must exist (value ignored)
```
