### ISSUE TITLE
Editor is not updating a modifed notification if the resource is deleted on cluster

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#644]
**Steps**:
1. ASSERT: have the following deployment existing on the cluster:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sise-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sise
  template:
    metadata:
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: quay.io/openshiftlabs/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
```
2. ASSERT: have it opened in an editor
3. EXEC: add a label to it 
```yaml
metadata:
  name: sise-deploy
  labels:
    jedi: yoda
```
4. ASSERT: notification appears in the editor, telling you to push to the cluster and update the resource that exists
<img width="917" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/abf34e43-ac9c-4dbf-81c7-b09534b80f03">
5. EXEC: delete the resource on the cluster   
 
<br/><br/>
**Result:**
The notification is not updated. It still tells you that you can push and update an existing resource.

**Expected Result:**
<img width="917" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/ff8a1f9c-89c8-4bcf-a13a-614aeac564ca">
The editor should show a different notification: it should tell you that the resource was deleted on the cluster and that pushing now would create the resource
