### ISSUE TITLE
subtask for #35: display Deployments

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#66]
here's how vscode is displaying them:
![image](https://user-images.githubusercontent.com/25126/85445494-c0577b00-b593-11ea-9f6f-831f1cd62460.png)

depends on #35 

here's a yaml to create a deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sise-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sise
  template:
    metadata:
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: quay.io/openshiftlabs/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
```
