### ISSUE TITLE
"Current namespace" of my old context is overwritten when I switch to a new context

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#669]
The following can be applied for any setup with 2 clusters

**Steps:**
1. ASSERT: have 2 contexts with different "namespace"s 
* minikube with namespace named "default"
* redhat sandbox with namespace "<YOUR_USERID>-dev" ("adietish-dev" for me)
```yaml
contexts:
- context:
    cluster: "api-sandbox-m3-1530-p1-openshiftapps-com:6443"
    namespace: "adietish-dev"
    user: "adietish/api-sandbox-m3-1530-p1-openshiftapps-com:6443"
  name: "adietish-dev/api-sandbox-m3-1530-p1-openshiftapps-com:6443/adietish"
- context:
    cluster: "minikube"
    namespace: "default"
    user: "minikube"
  name: "minikube"
```
2. ASSERT: have "minikube" set as current cluster/current namespace
3. EXEC: in tree: select "sandbox" and pick "Set as Current Cluster" in context menu
4. EXEC: open `~/.kube/config` in an editor and verify the "namespace" for "minikube"

**Result:**
"namespace" for "minikube" was set to "<YOUR_USERID>-dev" (was "default")
```yaml
- context:
    cluster: "minikube"
    namespace: "adietish-dev"
    user: "minikube"
  name: "minikube"
```
