### ISSUE TITLE
subtask to #35: display "Jobs"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#70]
depends on #35 

here's how vscode is displaying jobs:
![image](https://user-images.githubusercontent.com/25126/86024622-7fe17c80-ba2d-11ea-8f45-4216b28eb4c1.png)

here's a yaml to create a job:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
```
