### ISSUE TITLE
When pushing to create a new resource, notification says that resource was updated

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#708]
**Steps:**
1. ASSERT: make sure you dont have a pod named `alpine1` on your cluster
2. EXEC: open the following in an editor
```yaml
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jedi: "luke"
  name: "alpine1"
spec:
  containers:
  - image: "alpine"
    name: "alpine"
    ports:
    - containerPort: 8080
```
3. EXEC: push the editor to create a new pod on the cluster
4. ASSERT: new pod `alpine1` is created
5. EXEC: look at the notification in the editor, that tells you what was done on the cluster

**Result:**
<img width="903" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/50a196e4-5fe5-49d8-8ae6-379189284823">
You're told that the pod was `Updated`

**Expected result:**
You should be informed that the pod was `Created`
