### ISSUE TITLE
subtask to #35: display "CronJobs"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#71]
here's how vscode is displaying cronjobs:
![image](https://user-images.githubusercontent.com/25126/86026088-4873cf80-ba2f-11ea-84f5-1b995d91d775.png)

notice how jobs for cronjobs are listed in the jobs category.

here's a yaml to create a cronjob:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo sleeping....; sleep 5s; echo exiting...;
          restartPolicy: Never
```
