### ISSUE TITLE
As a user I want to know that my multi-resource editor successfully created the resource 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#710]
related to #658

In #658 we re-introduced the notification for a single-resource editor which tells the user that the resource was successfully created.
We're still missing this for the multi-resource editor. 

**Steps:**
1. EXEC: open the following in an editor:  
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: numberguess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numberguess
  template:
    metadata:
      labels:
        app: numberguess
    spec:
      containers:
        - name: my-numberguess
          image: numberguess:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: numberguess-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: numberguess
```
2. EXEC: push the editor to the cluster
3. ASSERT: the resources were successfully created

**Result:**
Nothing happens. There's no notification that tells you that the resource were successfully created. You only get a notification if something goes wrong and resources could not get created

**Expected result:**
I want to be informed that the resources were created on the cluster. Of course I'd also like to know of errors. So the notification should inform of both: success and errors. It's currently not evident how to inform properly as notifications currently only have single line and a single icon: they either inform of success (for the single resource editor) or errors (for both, the single resource editor or the multi resource editor)
