### ISSUE TITLE
"Remove Metadata Clutter" doesn't preseve order of resources, adds namespaces and turns "---" into "------"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#818]
related to:
* #710 

follows up on:
* #794

**Steps:**
1. EXEC: have the following in an editor:
```yaml
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "numberguess"
  labels:
    jedi: yoda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "numberguess"
  template:
    metadata:
      labels:
        app: "numberguess"
    spec:
      containers:
      - name: "my-numberguess"
        image: "numberguess:latest"
        ports:
        - name: "http"
          containerPort: 8081
          protocol: "TCP"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "numberguess-svc-22"
spec:
  ports:
  - name: "http-8081"
    port: 8081
    protocol: "TCP"
    targetPort: 8081
  selector:
    app: "numberguess"
```
2. EXEC: click "Remove Metadata Clutter in Editor" in the toolbar (most right icon in the toolbar)

**Result:**
1. the document now has the `Service` before the `Deployment`
2. the `Service` and the `Deployment`, both get a `namespace` property added (which they didnt have before):
```yaml
namespace: XXXX
```
3. the separator `---` is now `------` which makes the whole document marked with errors
```yaml
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "numberguess-svc-22"
  namespace: "adietish-dev"
spec:
  ports:
  - name: "http-8081"
    port: 8081
    protocol: "TCP"
    targetPort: 8081
  selector:
    app: "numberguess"
------
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    jedi: "yoda"
  name: "numberguess"
  namespace: "adietish-dev"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "numberguess"
  template:
    metadata:
      labels:
        app: "numberguess"
    spec:
      containers:
      - name: "my-numberguess"
        image: "numberguess:latest"
        ports:
        - name: "http"
          containerPort: 8081
          protocol: "TCP"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
```
