### ISSUE TITLE
Connt edit Secrets transparently in multi-resource documents

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#852]
follows up on #663

**Steps:**
1. EXEC: open the following yaml in an editor
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-07-14 - 15:53:39 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: openshift-quickstart
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: newsecret
  labels:
    jedi: yoda2
type: Opaque
data:
  username: dXNlcg==
  password: NTRmNDFkMTJlOGZh
```
2. EXEC: go to the secret and try to edit it like you can do when it is in it's own file.

**Result:**
I cannot edit the base64 values transparently. The inlay hints are missing
<img width="334" alt="Image" src="https://github.com/user-attachments/assets/53d3bce0-13a6-4648-a5d1-9b9d9c92d0cf" />

**Expected result:**
I should be able to transparently edit the base64 value transparently via the inlay hints that are clickable and open a value dialogue.
<img width="415" alt="Image" src="https://github.com/user-attachments/assets/b94d15e9-6f1f-4e6b-9bb6-bb0cd3f8c0ff" />
