### ISSUE TITLE
Cannot edit Secrets/Configmap values unencoded, transparently in json files or yaml files with quoted values

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#854]
follows up on #663
related to #852 

**Steps:**
1. EXEC: open a new editor with the following content:
```json
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "annotations": {},
    "name": "mytest34e"
  },
  "data": {
    "a": "dGVzdA==",
    "b": "dGVzdA=="
  }
}
```

**Result:**
It doesn't display inlay hint for "a" and "b". I thus cannot edit those values unencoded/transparently

**Expected result:**
The editor should display inlay hint for "a" and "b"..

Same is true for the following yaml with quoted values:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  string-value: "b2Jpd2Fu"
```
