### ISSUE TITLE
PVC with matchExpressions is NOT matching PV with labels that match the expression

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#878]
follows up on #642

**Steps:**
1. EXEC: paste the following in an editor for a yaml file:
```yaml
# --------------------------
# PersistentVolume 2 (targeted by PVC with matchExpressions)
# --------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-expressions
  labels:
    environment: production      # Label for matchExpressions
    region: us-west              # Label for matchExpressions (key existence)
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual       # Disables dynamic provisioning
  hostPath:
    path: /mnt/data-expressions
---
# --------------------------
# PVC 2: Uses matchExpressions
# --------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-expressions
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchExpressions:
      - key: environment
        operator: In             # Value must be in the list
        values: [production, staging]
      - key: region
        operator: Exists         # Key must exist (value ignored)
```
2. EXEC: go to the selector in the PVC and verify that it is matching the PV

**Result:**
The PVC reports "0 matching" for it's selector even though it's expression
```yaml
    matchExpressions:
      - key: environment
        operator: In             # Value must be in the list
        values: [production, staging]
      - key: region
        operator: Exists         # Key must exist (value ignored)
```
is matching the labels in the PV:
```yaml
  labels:
    environment: production      # Label for matchExpressions
    region: us-west              # Label for matchExpressions (key existence)
```
