### ISSUE TITLE
editor: Service selector should report matching labels in Deployment template

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#882]
follows up on #642

**Steps:** 
1. ASSERT: have the following in a yaml editor:
```yaml
apiVersion: apps/v1kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 874731470682e3f213506357d2f9887bab63be83
    app.quarkus.io/build-timestamp: 2025-04-05 - 22:16:28 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus3
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: code-with-quarkus3
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 874731470682e3f213506357d2f9887bab63be83
        app.quarkus.io/build-timestamp: 2025-04-05 - 22:16:28 +0000
      labels:
        app.kubernetes.io/name: code-with-quarkus3
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: minikube/adietish/code-with-quarkus3:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: code-with-quarkus3
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 874731470682e3f213506357d2f9887bab63be83
    app.quarkus.io/build-timestamp: 2025-04-05 - 22:16:28 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus3
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus3
spec:
  ports:
    - name: http
      nodePort: 31462
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: code-with-quarkus3
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
```
2. EXEC: navigate to the `selector` in the `Service` and verify how many resources are matching it:
<img width="631" alt="Image" src="https://github.com/user-attachments/assets/2a5cb048-104f-4b3d-ba5e-a42d48730079" />

**Result:**
It should repot 1 matching because the labels in the template for the `Deployment` match the selector.

<img width="631" alt="Image" src="https://github.com/user-attachments/assets/49ac9114-d45d-472f-b271-99ca7196864d" />
