### ISSUE TITLE
telemetry: no telemetry is sent upon clicking on a selector-/base64 hint

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#896]
We dont know how much these inlay hints are used because we dont have telemetry reporting users clicking them.

**Steps:**
1. EXEC: open an editor with the following content (has hints for base64 encoded values):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: dmFsdWUtMg0K
---
# Secret 1 - Database credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=          # base64 encoded "admin"
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"

---
# Secret 2 - TLS certificate
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk5vdCBBIFJlYWwgQ2VydGlmaWNhdGUhCg==  # base64 encoded fake cert
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpOb3QgQSBSZWFsIEtleSEK          # base64 encoded fake key
---
# Secret with binary data
apiVersion: v1
kind: Secret
metadata:
  name: binary-secret
type: Opaque
data:
  # Base64-encoded binary files (example shortened for readability)
  manual.pdf: |
    JVBERi0xLjUKJdDUxdgKNSAwIG9iago8PAovTGVuZ3RoIDE2NDMKICAgIC9GaWx0ZXIg
    L0ZsYXRlRGVjb2RlCj4+CnN0cmVhbQp4nO1dW2/iSBD+O0r/glWlVXU7F2MIuUjZVVYI
    iUQ4QiJcJIQEwiUQrgH++2bcxgbjGXfP2ZFO6wVij6enL9XV3dM9/9h5Z4wx
  binary-blob: |
    UEsDBBQAAAAIAAyqSlZHyZ1BCAEAAAgBAAANAAAAaW5kZXguaHRtbG2PwQrCMBBE7/2K
    yJ5KL1LQS0HwICgq9iC4m4Sm0KZJNxv89yY+QPB1mJ15M8xqTZ2p4y6Q7YkC0ZQxw7gg
    LmhJ5G1B2oK4yG0Jh8+5Jq4d7Y3jK7V0mIeBZkfH9Rj7YfCgP1f5ZxV6+QZQSwECHwAU
    AAAACAD6qkpWR8mdQQgBAAAIAQAADQAAAAAAAAAAAAAAAAAhAAAAaW5kZXguaHRtbFBLBQYAAAAAAQABADkAAABk
```
2. EXEC: click on one of the hints and verify in segment if an event was sent

**Result**
Currently no event is sent.

We dont know how much these inlay hints are used because we dont have telemetry reporting users clicking them.

**Steps:**
1. EXEC: open an editor with the following content (has hints for selectors and labels):
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 874731470682e3f213506357d2f9887bab63be83
    app.quarkus.io/build-timestamp: 2025-04-05 - 22:16:28 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: code-with-quarkus3
  name: code-with-quarkus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: code-with-quarkus3
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 874731470682e3f213506357d2f9887bab63be83
        app.quarkus.io/build-timestamp: 2025-04-05 - 22:16:28 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: code-with-quarkus3
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: minikube/adietish/code-with-quarkus3:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: code-with-quarkus3
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 874731470682e3f213506357d2f9887bab63be83
    app.quarkus.io/build-timestamp: 2025-04-05 - 22:16:28 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus3
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus3
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: code-with-quarkus3
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
```
2. EXEC: click on one of the hints and verify in segment if an event was sent

**Result**
Currently no event is sent.
